# Generated by Django 4.2.11 on 2026-03-02 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('paystack_id', models.CharField(blank=True, max_length=100)),
                ('access_code', models.CharField(blank=True, max_length=100)),
                ('authorization_url', models.URLField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=5)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Debit/Credit Card'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('mobile_money', 'Mobile Money'), ('qr', 'QR Code')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_bank', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_response', models.TextField(blank=True)),
                ('webhook_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
