# Generated by Django 4.2.11 on 2026-03-02 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_available', 'category'], name='food_items_is_avai_b62131_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['is_featured', 'is_available'], name='food_items_is_feat_4334cd_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['name'], name='food_items_name_7242ab_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'food_item'], name='cart_items_cart_id_f28d8b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'food_item')},
        ),
    ]
